
use std::error::Error;

pub fn part1(input: &str) -> Result<String, Box<dyn Error>> {
    Ok("great job".to_string())
}

pub fn part2(input: &str) -> Result<String, Box<dyn Error>> {
    Ok("great job".to_string())
}
